#!/usr/bin/env python3
"""Generate msg_define.hpp from sro_docs_vsro message markdown files."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MESSAGES = ROOT / "tools" / "silkroad-docs-main" / "docs" / "messages"
OUT_HPP = ROOT / "sro_ext_client" / "20-Program" / "sdk" / "net" / "msg_define.hpp"
OUT_CPP = ROOT / "sro_ext_client" / "20-Program" / "sdk" / "net" / "msg_define.cpp"


def sanitize(name: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_]", "_", name.upper())
    if name and name[0].isdigit():
        name = f"OP_{name}"
    return name


def main() -> None:
    entries: list[tuple[str, int, str]] = []
    for path in sorted(MESSAGES.glob("*.md")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        m = re.search(r"Opcode\s*\|\s*`(0x[0-9A-Fa-f]+)`", text)
        if not m:
            continue
        opcode = int(m.group(1), 16)
        title = path.stem
        parts = title.split("_", 1)
        if len(parts) == 2 and re.fullmatch(r"[0-9A-Fa-f]{4}", parts[0]):
            const_name = sanitize(parts[1])
        else:
            const_name = sanitize(title)
        entries.append((const_name, opcode, title))

    # One symbol per opcode; disambiguate duplicate names.
    seen_names: dict[str, int] = {}
    seen_opcodes: dict[int, tuple[str, int, str]] = {}
    unique: list[tuple[str, int, str]] = []
    for const_name, opcode, title in entries:
        if opcode in seen_opcodes:
            continue
        name = const_name
        if name in seen_names:
            seen_names[name] += 1
            name = f"{name}_{opcode:04X}"
        else:
            seen_names[name] = 1
        seen_opcodes[opcode] = (name, opcode, title)
        unique.append((name, opcode, title))
    entries = unique

    hpp_lines = [
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "// Generated by tools/gen_msg_define.py — do not edit.",
        "",
        "namespace ext_client::net::msg {",
        "",
    ]
    for const_name, opcode, title in entries:
        hpp_lines.append(f"  inline constexpr std::uint16_t {const_name} = 0x{opcode:04X}; // {title}")
    hpp_lines.extend(
        [
            "",
            "  [[nodiscard]] auto name(std::uint16_t opcode) -> const char*;",
            "",
            "} // namespace ext_client::net::msg",
            "",
        ]
    )

    cpp_lines = [
        '#include "pch.hpp"',
        '#include "sdk/net/msg_define.hpp"',
        "",
        "// Generated by tools/gen_msg_define.py — do not edit.",
        "",
        "namespace ext_client::net::msg {",
        "",
        "  auto name(std::uint16_t opcode) -> const char* {",
        "    switch (opcode) {",
    ]
    for const_name, opcode, title in entries:
        cpp_lines.append(f'      case 0x{opcode:04X}: return "{title}";')
    cpp_lines.extend(
        [
            "      default: return nullptr;",
            "    }",
            "  }",
            "",
            "} // namespace ext_client::net::msg",
            "",
        ]
    )

    OUT_HPP.parent.mkdir(parents=True, exist_ok=True)
    OUT_HPP.write_text("\n".join(hpp_lines), encoding="utf-8")
    OUT_CPP.write_text("\n".join(cpp_lines), encoding="utf-8")
    print(f"wrote {len(entries)} opcodes to {OUT_HPP} and {OUT_CPP}")


if __name__ == "__main__":
    main()
